/* ============================================================
   Oracle AI DP Portfolio — Churn Prediction
   Target: Autonomous Data Warehouse (ADW) / Oracle Database
   ============================================================ */

-- (Opcional) ajuste o schema antes:
-- ALTER SESSION SET CURRENT_SCHEMA = <SEU_SCHEMA>;

---------------------------------------------------------------
-- 1) STAGING: dados brutos (espelha o CSV)
---------------------------------------------------------------
CREATE TABLE STG_CLIENTES_CHURN (
  customer_id        NUMBER,
  idade              NUMBER,
  renda              NUMBER,
  plano              VARCHAR2(50),
  tempo_cliente      NUMBER,
  qtd_chamados       NUMBER,
  atraso_pagamento   NUMBER,
  churn              NUMBER,
  inserted_at        TIMESTAMP DEFAULT SYSTIMESTAMP
);

---------------------------------------------------------------
-- 2) CURATED: dados tratados para analytics/ML
--    Inclui coluna derivada e chaves/constraints simples
---------------------------------------------------------------
CREATE TABLE DIM_CLIENTES_CHURN (
  customer_id        NUMBER        NOT NULL,
  idade              NUMBER,
  renda              NUMBER,
  plano              VARCHAR2(50),
  tempo_cliente      NUMBER,
  qtd_chamados       NUMBER,
  atraso_pagamento   NUMBER,
  churn              NUMBER,
  faixa_renda        VARCHAR2(20),
  inserted_at        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_DIM_CLIENTES_CHURN PRIMARY KEY (customer_id)
);

---------------------------------------------------------------
-- 3) PREDIÇÕES: resultados do modelo
---------------------------------------------------------------
CREATE TABLE FATO_CHURN_PREDICOES (
  prediction_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_id        NUMBER        NOT NULL,
  churn_score        NUMBER(10,6)  NOT NULL,
  model_version      VARCHAR2(50)  DEFAULT 'v0.1.0',
  scored_at          TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_FATO_CHURN_PREDICOES PRIMARY KEY (prediction_id)
);

-- (Opcional) FK para reforçar relacionamento (depende se você sempre terá customer_id existente)
-- ALTER TABLE FATO_CHURN_PREDICOES
--   ADD CONSTRAINT FK_PRED_CUSTOMER
--   FOREIGN KEY (customer_id) REFERENCES DIM_CLIENTES_CHURN(customer_id);

---------------------------------------------------------------
-- 4) ÍNDICES úteis (opcional)
---------------------------------------------------------------
CREATE INDEX IDX_DIM_CLIENTES_PLANO ON DIM_CLIENTES_CHURN (plano);
CREATE INDEX IDX_PRED_CUSTOMER ON FATO_CHURN_PREDICOES (customer_id);
CREATE INDEX IDX_PRED_SCORED_AT ON FATO_CHURN_PREDICOES (scored_at);
